export {
  obligationKind,
  direction,
  threadSchema,
  contactSchema,
  obligationReasonSchema,
  obligationSchema,
  detectionConfigSchema,
  DEFAULT_DETECTION_CONFIG,
  type ObligationKind,
  type Direction,
  type Thread,
  type Contact,
  type ObligationReason,
  type Obligation,
  type DetectionConfig,
} from "./types.js";
export { detectObligations, daysBetween, rankObligation, type DetectInput } from "./detect.js";
export {
  applyIntentRules,
  fieldSkipped,
  intentRuleSchema,
  intentScopeSchema,
  parseIntentRule,
  predraftAllowed,
  promotionFor,
  resolveScope,
  type AppliedRules,
  type ContactRef,
  type IntentRule,
  type IntentRuleRecord,
  type IntentScope,
} from "./intents.js";
export {
  inferIntents,
  inferFromCorrections,
  REPEATED_CHANGES,
  type Correction,
  CONTACT_DISMISSALS,
  ACCOUNT_DISMISSALS,
  YOUNG_DISMISSALS,
  MAX_WAIT_DAYS,
  type Decision,
  type InferredIntent,
} from "./infer.js";
